version: '3'

services:
  timetrackerlegacy:
    image: 'alirizasaral/timetracker:1'
    ports:
           - "8070:8080"
  timetrackerwrapper:
    build: ./time-tracker-wrapper/
    ports:
           - "8887:8081"
    depends_on:
           - "timetrackerlegacy"
  timetrackerwebapp:
    build: ./time-tracker-webapp/
    depends_on:
           - "timetrackerwrapper"
    ports:
           - "8080:80"     
