FROM openjdk:11
MAINTAINER baeldung.com
COPY target/time-tracker-wrapper-0.0.1-SNAPSHOT.jar time-tracker-wrapper-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/time-tracker-wrapper-0.0.1-SNAPSHOT.jar"]
